trajectories:
  trajectory_random: 
    points_x: [0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 3.0]
    points_y: [0.0, 0.5, 2.5, 4.0, 7.0, 8.5, 10.0]
    points_z: [0.0, 1.5, 2.0, 2.0, 3.0, 2.0, 2.0]
    times: [0.0, 4.0, 6.0, 8.0, 10.0, 14.0, 18.0]
    ros_rate: 100.0
    method: "cubic_spline"

  trajectory_random_1: 
    points_x: [-1.0, -6.0, -10.0, -7.0, -4.5, -2.8, -2.0]
    points_y: [3.0, 0.0, -5.2, -6.3, -7.0, -9.5, -10.0]
    points_z: [2.5, 2.0, 2.2, 2.2, 2.3, 2.4, 2.7]
    times: [0.0, 3.0, 6.0, 9.0, 11.0, 13.0, 15.0]
    ros_rate: 100.0
    method: "minimum_snap"

  trajectory_random_2:
    points_x: [-2.5, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    points_y: [-9.0, -11.0, -12.5, -14.0, -16.0, -18.0, -20.0]
    points_z: [2.5, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 11.5, 13.5]
    ros_rate: 100.0
    method: "minimum_snap"

  trajectory_random_2_4:
    points_x: [-4.5, -3.0, -2.0, -2.0, -2.0, -2.0, -1.0]
    points_y: [-11.0, -13.0, -14.5, -16.0, -18.0, -20.0, -22.0]
    points_z: [2.8, 2.3, 2.3, 2.3, 3.3, 3.3, 3.3]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 11.5, 13.5]
    ros_rate: 100.0
    method: "minimum_snap"

  trajectory_random_2_5:
    points_x: [-0.5, 1.0, 2.0, 2.0, 2.0, 2.0, 3.0]
    points_y: [-11.0, -13.0, -14.5, -16.0, -18.0, -20.0, -22.0]
    points_z: [2.8, 2.3, 2.3, 2.3, 3.3, 3.3, 3.3]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 11.5, 13.5]
    ros_rate: 100.0
    method: "minimum_snap"

  trajectory_random_3:
    points_x: [1.0, 0.0, 0.0, -1.0, 1.0, 1.0, 0.0]
    points_y: [-17.0, -14.0, -11.0, -8.0, -5.0, -2.0, 0.0]
    points_z: [2.0, 3.0, 3.0, 3.0, 3.0, 2.5, 0.0]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 12.0, 15.0]
    ros_rate: 100.0
    method: "minimum_jerk"

  trajectory_random_3_2:
    points_x: [3.0, 2.0, 2.0, 1.0, 3.0, 3.0, 2.0]
    points_y: [-17.0, -14.0, -11.0, -8.0, -5.0, -2.0, 0.0]
    points_z: [2.0, 3.0, 3.0, 3.0, 3.0, 2.5, 0.0]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 12.0, 15.0]
    ros_rate: 100.0
    method: "minimum_jerk"

  trajectory_random_3_3:
    points_x: [-1.0, -2.0, -2.0, -3.0, -1.0, -1.0, -2.0]
    points_y: [-15.0, -12.0, -9.0, -6.0, -3.0, 0.0, 2.0]
    points_z: [2.0, 3.0, 3.0, 3.0, 3.0, 2.5, 0.0]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 12.0, 15.0]
    ros_rate: 100.0
    method: "minimum_jerk"

  trajectory_random_3_4:
    points_x: [-2.6, -3.6, -3.6, -4.6, -2.6, -2.6, -3.7]
    points_y: [-19.0, -16.0, -13.0, -10.0, -7.0, -4.0, -2.0]
    points_z: [2.3, 3.3, 3.3, 3.3, 3.3, 2.8, 0.3]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 12.0, 15.0]
    ros_rate: 100.0
    method: "minimum_jerk"

  trajectory_random_3_5:
    points_x: [4.6, 3.6, 3.6, 2.6, 4.6, 4.6, 3.7]
    points_y: [-19.0, -16.0, -13.0, -10.0, -7.0, -4.0, -2.0]
    points_z: [2.3, 3.3, 3.3, 3.3, 3.3, 2.8, 0.3]
    times: [0.0, 3.0, 5.0, 7.0, 9.0, 12.0, 15.0]
    ros_rate: 100.0
    method: "minimum_jerk"